automaticPlayerEngineTimescale: 7.0
automaticPlayerGameTimescale: 16.0
cargoAssignAllResourcesPerFrame: false
cargoSplitterOnlyUnits: true
developerTimesEaseRatio: 0.0500000007
doCargoChecksOnTick: true
enableConsole: true
errorThrowsException: false
fixSaves: false
fixStocks: false
gameSpeedMultiplier: 1.0
historyLoad: false
historySave: false
logCompleteCaller: false
logCorrectSourceLink: true
logCustomCallStackSeverity: TRACE
logFrame: false
logSeverity: TRACE
logTimestamp: true
logToCustomFile: false
logToUnity: true
logWhoString: true
logWhoType: true
musicOn: false
pauseAfterLoad: false
renderResourceLines: true
renderTrafficLines: true
rivalSpawnNearby: false
saveCopyLog: false
saveDumpState: false
showDebugPriorityLabels: false
showWayCosts: true
showWayFontSize: 80.0
slowdownInitialSpawns: false
smokeTestExitEditor: true
taskPriorityFromCargoTimedPriority: false
tempStageMusicEventsRotationMinutes: 10.0
textFilter: 
topicFilter:
